import type { UserSettings, WorkflowRule } from '../types';

/**
 * Triggers a webhook using our Node/Express backend proxy to overcome CORS restrictions.
 */
export async function triggerWebhookProxy(webhookUrl: string, event: string, data: any): Promise<boolean> {
  if (!webhookUrl) return false;
  try {
    const response = await fetch('/api/automation/trigger-webhook', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        webhookUrl,
        event,
        data,
      }),
    });

    if (!response.ok) {
      console.warn(`Webhook proxy call returned status: ${response.status}`);
      return false;
    }

    const result = await response.json();
    return result.success;
  } catch (error) {
    console.error('Error triggering webhook proxy:', error);
    return false;
  }
}

/**
 * Triggers global n8n webhooks configured in CRM settings.
 */
export async function triggerGlobalWebhook(
  userId: string,
  event: 'Lead Created' | 'Lead Status Changed' | 'Task Reminder',
  data: any
): Promise<void> {
  if (!userId) return;
  try {
    const response = await fetch(`/api/settings?userId=${encodeURIComponent(userId)}`);
    if (!response.ok) return;

    const resData = await response.json();
    const settings = resData.settings as UserSettings;
    if (!settings) return;

    let url: string | undefined;

    switch (event) {
      case 'Lead Created':
        url = settings.n8nLeadCreatedUrl;
        break;
      case 'Lead Status Changed':
        url = settings.n8nStatusChangedUrl;
        break;
      case 'Task Reminder':
        url = settings.n8nTaskReminderUrl;
        break;
    }

    if (url) {
      console.log(`Triggering global n8n Webhook for event: ${event}`);
      await triggerWebhookProxy(url, event, data);
    }
  } catch (error) {
    console.error(`Error in triggerGlobalWebhook for ${event}:`, error);
  }
}

/**
 * Evaluates active custom CRM workflows for a user and triggers matches.
 */
export async function triggerWorkflowAutomations(
  userId: string,
  triggerEvent: 'Lead Created' | 'Lead Status Changed',
  checkConditionValue: string,
  payload: any
): Promise<void> {
  if (!userId) return;
  try {
    const response = await fetch(`/api/workflows?userId=${encodeURIComponent(userId)}`);
    if (!response.ok) return;

    const resData = await response.json();
    const workflowsData = resData.workflows as WorkflowRule[];
    if (!workflowsData || !Array.isArray(workflowsData)) return;

    // Filter active rules for the given trigger event
    const activeRules = workflowsData.filter(
      w => w.isActive && w.triggerEvent === triggerEvent
    );

    for (const rule of activeRules) {
      // Validate configuration value if status changes
      if (triggerEvent === 'Lead Status Changed' && rule.triggerCondition !== checkConditionValue) {
        continue; // condition doesn't match
      }

      console.log(`Executing automation rule: ${rule.name} of type: ${rule.actionType}`);

      if (rule.actionType === 'Trigger n8n Webhook' && rule.n8nWebhookUrl) {
        // Trigger n8n webhook
        await triggerWebhookProxy(rule.n8nWebhookUrl, triggerEvent, payload);
      } else if (rule.actionType === 'Create Task' && rule.taskTitle) {
        // Automatically create a fallback follow-up task
        const leadName = payload.name || 'N/A';
        const leadId = payload.id || '';
        await fetch('/api/tasks', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            title: rule.taskTitle,
            description: `Auto-generated by workflow: "${rule.name}" for Lead: ${leadName}`,
            leadId,
            leadName,
            dueDate: Date.now() + 86400000, // Due in 1 day
            status: 'Pending',
            userId,
            taskType: 'General'
          })
        });
      }
    }
  } catch (error) {
    console.error(`Error executing workflow automations for event ${triggerEvent}:`, error);
  }
}

/**
 * Evaluates active 'Keywords Match' workflow rules for a lead and automatically updates tags if needed.
 */
export async function evaluateKeywordsTrigger(userId: string, lead: any): Promise<any> {
  if (!userId || !lead) return lead;
  try {
    const response = await fetch(`/api/workflows?userId=${encodeURIComponent(userId)}`);
    if (!response.ok) return lead;

    const resData = await response.json();
    const workflowsData = resData.workflows as WorkflowRule[];
    if (!workflowsData || !Array.isArray(workflowsData)) return lead;

    // Filter active 'Keywords Match' rules
    const activeRules = workflowsData.filter(
      w => w.isActive && w.triggerEvent === 'Keywords Match'
    );

    if (activeRules.length === 0) return lead;

    const notes = lead.notes || '';
    const email = lead.email || '';
    
    let tagsToSet = Array.isArray(lead.tags) ? [...lead.tags] : [];
    let hasChanges = false;

    // Helper to see if any keyword exists in a text
    const checkMatch = (text: string, keywordsCsv: string): boolean => {
      if (!text || !keywordsCsv) return false;
      const keywords = keywordsCsv.split(',').map(k => k.trim().toLowerCase()).filter(Boolean);
      const textLower = text.toLowerCase();
      return keywords.some(kw => textLower.includes(kw));
    };

    for (const rule of activeRules) {
      if (!rule.triggerCondition) continue;
      
      const isMatch = checkMatch(notes, rule.triggerCondition) || checkMatch(email, rule.triggerCondition);

      if (isMatch) {
        // Tag to add from rule (stored in taskTitle/task_title)
        const tagsToAdd = (rule.taskTitle || '').split(',').map(t => t.trim()).filter(Boolean);
        const originalLength = tagsToSet.length;
        
        // Merge and uniquely filter
        tagsToSet = Array.from(new Set([...tagsToSet, ...tagsToAdd]));
        
        if (tagsToSet.length > originalLength) {
          hasChanges = true;
          console.log(`Keywords Match rule "${rule.name}" triggered. Adding tags: ${tagsToAdd.join(', ')}`);
        }
      }
    }

    if (hasChanges) {
      // Promptly save the new tags to the lead
      const updateResponse = await fetch(`/api/leads/${lead.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ tags: tagsToSet })
      });
      if (updateResponse.ok) {
        const updateData = await updateResponse.json();
        return updateData.lead;
      }
    }
  } catch (error) {
    console.error('Error evaluating keywords trigger:', error);
  }
  return lead;
}


